### ISSUE TITLE
cannot read file from S3 within parallelized loop

### ISSUE THREAD

**Issue by cfrick13** [bioio-devs/bioio#71]
### Describe the Bug

I try to use bioio to read image data in a parallelized loop. It works if the file is on a local network but fails (just hangs and stops without throwing an error) if the file is on S3. (note: the S3 file can be read if it is not run in parallel just fine)

### Expected Behavior

I expect the same behavior for a file that is local or that is on S3.

### Reproduction

```python
# now try to process this image in parallel
from multiprocessing import Pool
from tqdm import tqdm
from bioio import BioImage
import bioio_ome_zarr

NWORKERS = 4

def nonparallel_read(file_path,location):
    reader = BioImage(file_path, reader = bioio_ome_zarr.Reader)
    lazy_img = reader.get_image_dask_data("ZYX",C=0,T=0)
    img = lazy_img.compute()
    print(f"     {location} nonparallel read successful {img.shape}")

def parallel_read(filepath,location,nworkers):
    reader = BioImage(filepath, reader = bioio_ome_zarr.Reader)
    args = [(reader,x,location) for x in range(NWORKERS*2)]
    with Pool(nworkers) as p:
        # outlist = list(tqdm(p.imap_unordered(parallel_read_execute, args), total=len(args), desc="Processing image timepoints"))
        outlist = list(p.imap_unordered(parallel_read_execute, args))
    print(f'     {location} (reader outside parallel) successful', len(outlist),outlist[0])

def parallel_read_execute(args):
        reader, T, location = args
        lazy_img = reader.get_image_dask_data("ZYX",C=0,T=T)
        return lazy_img.shape

def reader_inside_parallel_read(filepath,location,nworkers):
    args = [(filepath,x,location) for x in range(NWORKERS*2)]
    with Pool(nworkers) as p:
        # outlist = list(tqdm(p.imap_unordered(reader_inside_parallel_read_execute, args), total=len(args), desc="Processing image timepoints"))
        outlist = list(p.imap_unordered(reader_inside_parallel_read_execute, args))
    
    print(f'     {location} (reader inside parallel) successful', len(outlist),outlist[0])

def reader_inside_parallel_read_execute(args):
        filepath, T, location = args
        reader = BioImage(filepath, reader = bioio_ome_zarr.Reader, use_plugin_cache=False)
        lazy_img = reader.get_image_dask_data("ZYX",C=0,T=T)
        return lazy_img.shape

# now try to process the image in parallel
def test_zarr_file(file_path,location):
    print(f"Testing {location} file")
    # test nonparallel read of image from specified filepath
    nonparallel_read(file_path,location)
    reader_inside_parallel_read(file_path,location,NWORKERS) # code hangs here for S3 files
    parallel_read(file_path,location,NWORKERS) # code hangs here for S3 files
    print(f"SUCCESS: {location} file")


if __name__ == "__main__":
    #%%
    local_file = "//allen/aics/assay-dev/computational/data/release/nuc-morph-dataset/hipsc_fov_nuclei_timelapse_dataset/hipsc_fov_nuclei_timelapse_data_used_for_analysis/baseline_colonies_fov_timelapse_dataset/20200323_06_medium/seg.ome.zarr"
    s3_file = 'https://allencell.s3.amazonaws.com/aics/nuc-morph-dataset/hipsc_fov_nuclei_timelapse_dataset/hipsc_fov_nuclei_timelapse_data_used_for_analysis/baseline_colonies_fov_timelapse_dataset/20200323_06_medium/seg.ome.zarr'
    for file,location in [(local_file,'local'),(s3_file,'s3')]:
        test_zarr_file(file,location)
        print()
```

```
Testing local file
     local nonparallel read successful (109, 3120, 4560)
     local (reader inside parallel) successful 8 (109, 3120, 4560)
     local (reader outside parallel) successful 8 (109, 3120, 4560)
SUCCESS: local file

Testing s3 file
     s3 nonparallel read successful (109, 3120, 4560)
```

### Environment
basic details
```
python = 3.9.18
"bioio-ome-zarr=1.0.1",
"bioio=1.0.2",
"bioio-base=1.0.1",
```

detailed details
```
requires-python = ">=3.9,<3.12"
urls = {Repository = "https://https://github.com/AllenCell/nuc-morph-analysis"}
version = "1.0.0"
dependencies = [
    "jupyter",
    "ipykernel",
    "itk",
    "itkwidgets",
    "ipywidgets",
    "numpy",
    "pandas",
    "tqdm",
    "panel",
    "moviepy",
    "matplotlib",
    "plotly",
    "scikit-image",
    "scikit-learn",
    "seaborn",
    "scipy>=1.10",
    "imageio",
    "statsmodels",
    "pacmap",
    "bigtree",
    "argparse",
    "pillow",
    "pathlib",
    "aicsimageio>=4.14.0",
    "ipython>=8.18.1",
    "av>=10.0.0",
    "shapely>=2.0.2",
    "fire>=0.5.0",
    "pyarrow>=15.0.0",
    "termcolor>=2.4.0",
    "cvapipe-analysis>=0.2.0",
    "vtk-osmesa>=9.3.0",
    "colorizer-data @ git+https://github.com/allen-cell-animated/colorizer-data.git@v1.2.0",
    "bioio-ome-zarr>=1.0.1",
    "bioio>=1.0.2",
    "bioio-base>=1.0.1",
    "colour-science>=0.4.4",
    "opencv-python-headless>=4.10.0.82",
    "yarl>=1.9.4",
]
```

-   OS Version: SLURM
-   bioio Version: 1.0.2

**Comment by cfrick13** [comment]
Interestingly I cannot reproduce this issue on my macbook pro. Here everything runs successfully. 
OS X Sonoma 14.5

```
Testing local file
     local nonparallel read successful (109, 3120, 4560)
     local (reader inside parallel) successful 8 (109, 3120, 4560)
     local (reader outside parallel) successful 8 (109, 3120, 4560)
SUCCESS: local file

Testing s3 file
     s3 nonparallel read successful (109, 3120, 4560)
     s3 (reader inside parallel) successful 8 (109, 3120, 4560)
     s3 (reader outside parallel) successful 8 (109, 3120, 4560)
SUCCESS: s3 file
```


```
dependencies = [
    "bioio>=1.0.3",
    "jupyter>=1.0.0",
    "aicspylibczi>=3.2.0",
    "bioio-czi>=1.0.1",
    "matplotlib>=3.9.1",
    "bioio-tifffile>=1.0.0",
    "bioio-ome-tiff>=1.0.0",
    "ipykernel>=6.29.5",
    "pyopencl>=2024.2.7",
    "bioio-ome-zarr>=1.0.1",
]
requires-python = "==3.9.*"
```

**Comment by cfrick13** [comment]
running in an identical environment on slurm as the one on my mac still ran into the issue. 

```
Testing local file
     local nonparallel read successful (109, 3120, 4560)
     local (reader inside parallel) successful 8 (109, 3120, 4560)
     local (reader outside parallel) successful 8 (109, 3120, 4560)
SUCCESS: local file

Testing s3 file
     s3 nonparallel read successful (109, 3120, 4560)
```

```
dependencies = [
    "bioio>=1.0.3",
    "jupyter>=1.0.0",
    "aicspylibczi>=3.2.0",
    "bioio-czi>=1.0.1",
    "matplotlib>=3.9.1",
    "bioio-tifffile>=1.0.0",
    "bioio-ome-tiff>=1.0.0",
    "ipykernel>=6.29.5",
    "pyopencl>=2024.2.7",
    "bioio-ome-zarr>=1.0.1",
]
requires-python = "==3.9.*"
```

**Comment by evamaxfield** [comment]
Can we back up a bit and figure out what you are trying to do from a basic level? Do you want to speed up the read time by parallelizing the read? Do you want to read and process individual planes ZYX stacks of a timeseries image?

In either case, I don't think you want to be using `multiprocessing.Pool` and would in general suggest using `distributed.LocalCluster` (or better `dask_jobqueue.SLURMCluster`, @toloudis may have more up-to-date knowledge on this -- this is what I used years ago while still at Allen)

My answer may change based on your response of "what is the end goal of this work"

**Comment by toloudis** [comment]
You make a good point that using dask cluster could work better "natively".  But on our Slurm cluster, I don't think you can create a dask cluster that spans slurm nodes.  You definitely can create a localcluster that multithreads on a single node. 

We have had dask fall over badly when given significant amounts of work to do with localclusters on slurm.  So you still have to carve up the job into pieces.

But I also don't think there's anything inherently wrong with trying to use `multiprocessing`.  Another interesting test might be to use get_image_data (no dask) with `multiprocessing`.  If the granularity is independent multiples of zarr chunks then you should get good parallel performance.

Still, we don't know why it works on one machine but not on another.  That's being investigated and tbd.

**Comment by cfrick13** [comment]
update: running on an A100 compute node running Ubuntu 20.04 also hangs/stalls when trying to read from S3 in parallel. 
(same python env details as above)
```
Testing local file
   local nonparallel read successful (109, 3120, 4560)
   local (reader inside parallel) successful 8 (109, 3120, 4560)
   local (reader outside parallel) successful 8 (109, 3120, 4560)
SUCCESS: local file

Testing s3 file
   s3 nonparallel read successful (109, 3120, 4560)
```

**Comment by cfrick13** [comment]
> Can we back up a bit and figure out what you are trying to do from a basic level? Do you want to speed up the read time by parallelizing the read? Do you want to read and process individual planes ZYX stacks of a timeseries image?
 
Hi @evamaxfield ,  I am trying to speed up IO and processing by reading and processing individual ZYX timepoints in parallel.  I'd be happy to hear your thoughts on how to achieve this best. 

the line of code I am trying to run in parallel is here:

https://github.com/AllenCell/nuc-morph-analysis/blob/023b0d4a2a08836300a0f62b6340c55178d341a3/nuc_morph_analysis/lib/preprocessing/twoD_zMIP_area/watershed_workflow.py#L55

PR with a very brief overview of the outcome of this code is here:
https://github.com/AllenCell/nuc-morph-analysis/pull/20

**Comment by cfrick13** [comment]
Here is the traceback when the job is killed:

```
Testing s3 file
     s3 nonparallel read successful (109, 3120, 4560)
^CProcess ForkPoolWorker-11:
Process ForkPoolWorker-10:
Process ForkPoolWorker-9:
Process ForkPoolWorker-12:
Traceback (most recent call last):
  File "/home/chris.frick/.pyenv/versions/3.9.19/lib/python3.9/multiprocessing/pool.py", line 853, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/allen/aics/assay-dev/users/Frick/PythonProjects/repos/LLS_repo/simple_lattice_test/simple_lattice/zarr_test.py", line 54, in <module>
    test_zarr_file(file,location)
  File "/allen/aics/assay-dev/users/Frick/PythonProjects/repos/LLS_repo/simple_lattice_test/simple_lattice/zarr_test.py", line 46, in test_zarr_file
    reader_inside_parallel_read(file_path,location,NWORKERS) # code hangs here for S3 files
  File "/allen/aics/assay-dev/users/Frick/PythonProjects/repos/LLS_repo/simple_lattice_test/simple_lattice/zarr_test.py", line 31, in reader_inside_parallel_read
    outlist = list(p.imap_unordered(reader_inside_parallel_read_execute, args))
  File "/home/chris.frick/.pyenv/versions/3.9.19/lib/python3.9/multiprocessing/pool.py", line 858, in next
    self._cond.wait(timeout)
  File "/home/chris.frick/.pyenv/versions/3.9.19/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by cfrick13** [comment]
I also just tested this on a Windows 10 machine. It works fine. 

```
Testing local file
     local nonparallel read successful (109, 3120, 4560)
     local (reader inside parallel) successful 8 (109, 3120, 4560)
     local (reader outside parallel) successful 8 (109, 3120, 4560)
SUCCESS: local file

Testing s3 file
     s3 nonparallel read successful (109, 3120, 4560)
     s3 (reader inside parallel) successful 8 (109, 3120, 4560)
     s3 (reader outside parallel) successful 8 (109, 3120, 4560)
SUCCESS: s3 file
```

```
Windows 10
Python 3.9.19

pip freeze
aicspylibczi==3.2.0
aiobotocore==2.13.2
aiohappyeyeballs==2.4.0
aiohttp==3.10.5
aioitertools==0.11.0
aiosignal==1.3.1
annotated-types==0.7.0
asciitree==0.3.3
async-timeout==4.0.3
attrs==24.2.0
bioio==1.1.0
bioio-base==1.0.4
bioio-czi==1.0.1
bioio-ome-tiff==1.0.0
bioio-ome-zarr==1.1.0
bioio-tifffile==1.0.0
botocore==1.34.131
certifi==2024.7.4
charset-normalizer==3.3.2
click==8.1.7
cloudpickle==3.0.0
colorama==0.4.6
contourpy==1.2.1
cycler==0.12.1
dask==2024.8.0
distributed==2024.8.0
elementpath==4.4.0
fasteners==0.19
fonttools==4.53.1
frozenlist==1.4.1
fsspec==2024.6.1
idna==3.7
imagecodecs==2024.6.1
imageio==2.27.0
imageio-ffmpeg==0.5.1
importlib_metadata==8.4.0
importlib_resources==6.4.4
intel-cmplr-lic-rt==2024.2.1
intel-opencl-rt==2024.2.1
itkwasm==1.0b178
itkwasm-downsample==1.4.0
itkwasm-downsample-wasi==1.4.0
Jinja2==3.1.4
jmespath==1.0.1
kiwisolver==1.4.5
lazy_loader==0.4
locket==1.0.0
lxml==4.9.4
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.2
mdurl==0.1.2
msgpack==1.0.8
multidict==6.0.5
networkx==3.2.1
ngff-zarr==0.8.5
numcodecs==0.12.1
numpy==1.26.4
ome-types==0.5.1.post1
ome-zarr==0.9.0
packaging==24.1
pandas==2.2.2
partd==1.4.2
pillow==10.4.0
platformdirs==4.2.2
psutil==6.0.0
pydantic==2.8.2
pydantic-compat==0.1.2
pydantic_core==2.20.1
Pygments==2.18.0
pyopencl==2024.2.7
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytools==2024.1.13
pytz==2024.1
PyYAML==6.0.2
requests==2.32.3
rich==13.7.1
rich-argparse==1.5.2
s3fs==2024.6.1
scikit-image==0.22.0
scipy==1.13.1
semver==3.0.2
six==1.16.0
sortedcontainers==2.4.0
tbb==2021.13.1
tblib==3.0.0
tifffile==2024.8.10
toolz==0.12.1
tornado==6.4.1
typing_extensions==4.12.2
tzdata==2024.1
urllib3==1.26.19
wasmtime==24.0.0
wrapt==1.16.0
xarray==2024.7.0
xmlschema==3.3.2
xsdata==24.3.1
yarl==1.9.4
zarr==2.18.2
zict==3.0.0
zipp==3.20.0
```

**Comment by toloudis** [comment]
Issue seems to be resolved by using:

```
    with get_context("spawn").Pool() as pool:
```

**Comment by cfrick13** [comment]
Can confirm that this fixes the issue!

**Comment by SeanLeRoy** [comment]
Nice, closing out
